version: 2.1

node-image: &node-image
  docker:
    - image: circleci/node:16.4.2

jobs:
  build-and-push-image:
    <<: *node-image
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update && sudo apt-get install -y docker
      - run:
          name: Install awscliv2
          command: |
            sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            sudo unzip awscliv2.zip && \
            sudo ./aws/install
      - run:
          name: Build and push Docker image
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 001512705144.dkr.ecr.us-west-2.amazonaws.com
            docker build -t udacity-devops-capstone .
            docker tag udacity-devops-capstone:latest 001512705144.dkr.ecr.us-west-2.amazonaws.com/udacity-devops-capstone:latest
            docker push 001512705144.dkr.ecr.us-west-2.amazonaws.com/udacity-devops-capstone:latest

workflows:
  default:
    jobs:
      - build-and-push-image