version: 2.1

node-image: &node-image
  docker:
    - image: circleci/node:16.4.2

jobs:
  build:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run build
          command: npm run build
      - save_cache:
          paths: [/home/circleci/project/node_modules]
          key: build-{{ checksum "package.json" }}
  lint:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{ checksum "package.json" }}
      - run:
          name: Lint code
          command: npm install && npm run lint
  push-docker-image-to-ecr:
    <<: *node-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install awscliv2
          command: |
            sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            sudo unzip awscliv2.zip && \
            sudo ./aws/install
      - run:
          name: Build and push Docker image
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 001512705144.dkr.ecr.us-west-2.amazonaws.com
            docker build -t udacity-devops-capstone .
            docker tag udacity-devops-capstone:latest 001512705144.dkr.ecr.us-west-2.amazonaws.com/udacity-devops-capstone:latest
            docker push 001512705144.dkr.ecr.us-west-2.amazonaws.com/udacity-devops-capstone:latest

workflows:
  default:
    jobs:
      - build
      - lint:
          requires:
            - build
      - push-docker-image-to-ecr:
          requires:
            - lint